version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: stock_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stock_analysis
      MYSQL_USER: stock_user
      MYSQL_PASSWORD: stock_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - stock_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stock_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - stock_network
    restart: unless-stopped

  python_app:
    build: .
    container_name: stock_python_app
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    depends_on:
      - mysql
    networks:
      - stock_network
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  stock_network:
    driver: bridge